config/routes.rb
CMUEducation::Application.routes.draw do
  resources :search, :only => [:index]
  resources :deliverables
  match '/people/:id/my_deliverables' => 'deliverables#my_deliverables', :as => :my_deliverables
  match '/deliverables/:id/feedback' => 'deliverables#edit_feedback', :as => :deliverable_feedback
  match '/sponsored_projects/:id/archive' => 'sponsored_projects#archive', :as => :archive_sponsored_project
  match '/sponsored_project_sponsors/:id/archive' => 'sponsored_project_sponsors#archive', :as => :archive_sponsored_project_sponsor
  match '/sponsored_project_allocations/:id/archive' => 'sponsored_project_allocations#archive', :as => :archive_sponsored_project_allocation
  resources :sponsored_projects
  resources :sponsored_project_sponsors
  resources :sponsored_project_allocations
  resources :sponsored_project_efforts
  match 'delayed_system_jobs/' => 'delayed_system_jobs#index'
  resources :delayed_system_jobs
  resources :rss_feeds
  resources :curriculum_comment_types
  match '/curriculum_comments/test_page' => 'curriculum_comments#test_page'
  resources :curriculum_comments
  resources :scotty_dog_sayings
  resources :project_types
  resources :projects
  resources :task_types
  match '/effort_logs/update_task_type_select' => 'effort_logs#update_task_type_select', :as => :update_task_type_select
  match '/effort_logs/effort_for_unregistered_courses' => 'effort_logs#effort_for_unregistered_courses'
  resources :effort_logs
  resources :effort_log_line_items
  resources :course_numbers
  resources :course_configurations
  match '/courses/current_semester' => 'courses#current_semester', :as => :current_semester
  match '/courses/next_semester' => 'courses#next_semester', :as => :next_semester
  constraints({:id => /.*/}) do
    resources :mailing_lists
    resources :pages do
      collection do
        post :reposition
      end
    end
  end

  resources :course_navigations
  resources :courses do
    resources :teams do
    end
    member do
      get :configure
    end
  end

  match '/courses/:course_id/peer_evaluations' => 'peer_evaluation#index_for_course', :via => :get, :as => "peer_evaluations"
  match '/courses/:course_id/teams/:id/peer_evaluation' => 'teams#peer_evaluation', :via => :get, :as => "peer_evaluation"
  match '/courses/:course_id/teams/:id/peer_evaluation_update' => 'teams#peer_evaluation_update', :via => :post, :as => "peer_evaluation_update"
  match 'peer_evaluation/edit_setup/:id' => 'peer_evaluation#edit_setup', :as => :setup_peer_evaluation
  match 'peer_evaluation/edit_evaluation/:id' => 'peer_evaluation#edit_evaluation', :as => :edit_peer_evaluation
  match 'peer_evaluation/edit_report/:id' => 'peer_evaluation#edit_report', :as => :report_peer_evaluation

  match '/effort_reports/campus_week' => 'effort_reports#campus_week'
  match '/effort_reports/campus_semester' => 'effort_reports#campus_semester'
  match '/effort_reports/course/:course_id' => 'effort_reports#course'
  resources :effort_reports
  match '/people/class_profile' => 'people#class_profile'
  match '/people/advanced' => 'people#advanced' #Just in case anyone bookmarked this url
  match '/people/photo_book' => 'people#photo_book'
  match '/people/:id/my_courses' => 'people#my_courses', :as => :my_courses
  match '/people/:id/my_teams' => 'people#my_teams', :as => :my_teams
  resources :people
  resources :suggestions
  match '/teams' => 'teams#index_all', :as => :teams

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  #resources :users
  #resource :user_session

  #match '/login_google' => 'user_sessions#login_google', :as => :login_google
  #match '/logout' => "user_sessions#destroy", :as => :logout


  match '/load_chart' => 'effort_reports#load_chart', :as => :load_chart
  match 'people/twiki/:twiki_name' => 'people#show_by_twiki'
  match 'twiki/teams' => 'teams#twiki_index'
  match 'twiki/teams/new' => 'teams#twiki_new'
  match 'courses/:course_id/teams_photos' => 'teams#index_photos'
  match 'courses/:course_id/past_teams_list' => 'teams#past_teams_list', :as => :past_teams_list
  match 'courses/:course_id/export_to_csv' => 'teams#export_to_csv'
  match 'courses/:course_id/deliverables' => 'deliverables#index_for_course', :as => :course_deliverables
  match 'effort_reports/:id/week/:week' => 'effort_reports#show_week'
  match '/:controller(/:action(/:id))'
  match '/new_features' => 'welcome#new_features', :as => :new_features
  match '/config' => 'welcome#configuration', :as => :config
  match '/' => 'welcome#index', :as => :root
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  before_filter :authenticate_user!, :except => [:show_by_twiki, :edit]

# Floating box source: http://roshanbh.com.np/2008/07/top-floating-message-box-using-jquery.html

  layout 'cmu_sv'

#  auto_complete_for :person, :human_name
#  protect_from_forgery :only => [:create, :update, :destroy] #required for auto complete to work

# GET /people
# GET /people.xml
  def index
    if params[:term] #Ajax call for autocomplete
                     #if database is mysql
                     #@people = Person.find(:all, :conditions => ['human_name LIKE ?', "%#{params[:term]}%"])
      @people = Person.find(:all, :conditions => ['human_name ILIKE ?', "%#{params[:term]}%"])
    else
      @people = Person.find(:all, :conditions => ['is_active = ?', true], :order => "first_name ASC, last_name ASC")
    end


    respond_to do |format|
      format.html { render :html => @people }
      format.json { render :json => @people.collect { |person| person.human_name }, :layout => false }
    end
  end

  def advanced
    index
  end

  def photo_book
    index
  end


  # GET /people/1
  # GET /people/1.xml
  # GET /people/AndrewCarnegie
  # GET /people/AndrewCarnegie.xml
  def show
    if (params[:id].to_i != 0) #This is a string
      @person = Person.find_by_twiki_name(params[:id].to_i)
    else #This is a number
      @person = Person.find(params[:id])
    end
    @person.revert_to params[:version_id] if params[:version_id]

    respond_to do |format|
      if @person.nil?
        flash[:error] = "Person with an id of #{params[:id]} is not in this system."
        format.html { redirect_to(people_url) }
        format.xml { render :xml => @person.errors, :status => :unprocessable_entity }
      else
        format.html # show.html.erb
        format.xml { render :xml => @person }
      end
    end
  end

  # GET /people/twiki/AndrewCarnegie
  # GET /people/twiki/AndrewCarnegie.xml
  def show_by_twiki
    redirect_to :action => 'robots' if robot?
    host = get_http_host()
    if !(host.include?("info.sv.cmu.edu") || host.include?("info.west.cmu.edu")) && (current_user.nil?)
      flash[:error] = 'You don' 't have permissions to view this data.'
      redirect_to(people_url)
      return
    end

    @machine_name = "http://rails.sv.cmu.edu"

    twiki_name = params[:twiki_name]
    @person = Person.find_by_twiki_name(twiki_name)

    if @person.nil?
      @person = Person.new
      @person.twiki_name = twiki_name
      names = Person.parse_twiki(twiki_name)
      @person.first_name = names[0] unless names.nil?
      @person.last_name = names[1] unless names.nil?
      @person.webiso_account = Time.now.to_f.to_s #This line probably not necessary since I added it to Person.before_validation
      @person.is_active = true
      @person.updated_by_user_id = current_user.id if current_user
      @person.image_uri = "/images/mascot.jpg"
      @person.local_near_remote = "Unknown"
      @person.save

      options = {:to => "help@sv.cmu.edu", :cc => "todd.sedano@sv.cmu.edu",
                 :subject => "rails user account automatically created for #{twiki_name}",
                 :message => "Action Required: update this user's andrew id in the rails database.<br/><br/>The twiki page for #{twiki_name} was rendered on the twiki server. This page asked rails to generate user data from the rails database. This user did not exist in the rails database, so rails created it.<br/>Note: this person can not edit their own information until their record is updated with their andrew login.<br/><br/>first_name: #{@person.first_name}<br/>last_name: #{@person.last_name}<br/>email: #{@person.email}<br/>is_active?: #{@person.is_active?}",
                 :url_label => "Edit this person's information",
                 :url => "http://rails.sv.cmu.edu" + edit_person_path(@person)
      }
      GenericMailer.email(options).deliver
    end

    respond_to do |format|
      if @person.nil?
        flash[:error] = "Person #{params[:twiki_name]} is not in this system."
        format.html { redirect_to(people_url) }
        format.xml { render :xml => @person.errors, :status => :unprocessable_entity }
      else
        format.html { render :html => @person, :layout => false } # show.html.erb
        format.xml { render :xml => @person }
      end
    end
  end


  # GET /people/new
  # GET /people/new.xml
  def new
    if !(current_user.is_admin? || current_user.is_staff?)
      flash[:error] = "You don't have permission to do this action."
    end

    @person = Person.new
    @person.is_active = true

    if Rails.env.development?
      @domain = GOOGLE_DOMAIN
    else
      @domain = "sv.cmu.edu"
    end

    @strength_themes = StrengthTheme.all


    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @person }
    end
  end

  # GET /people/1/edit
  def edit
#    if !(current_user.is_admin? || current_user.is_staff?)
#      flash[:error] = "You don't have permission to do this action."
#      redirect_to(people_url) and return
#    end

    @person = Person.find(params[:id])
    @strength_themes = StrengthTheme.all
    redirect_to(@person)
  end

  # POST /people
  # POST /people.xml
  def create
    if !(current_user.is_admin? || current_user.is_staff?)
      flash[:error] = "You don't have permission to do this action."
      redirect_to(people_url) and return
    end

    @person = Person.new(params[:person])
    @person.updated_by_user_id = current_user.id
    @person.image_uri = "/images/mascot.jpg"
    @person.biography = "<p>I was raised by sheepherders on the hills of BoingBoing while they were selling chunky bacon. Because I have a ring, I need help with putting on my clothes. After working hard they promoted me to garbage man. They told me the reason for this new responsibility was show me the money. I looked for a treasure map and tools, but I never did find the fourteen minutes. People's trash clearly isn't multitudinous. I hope to put my real biography here one day.</p>"
    if @person.is_student
      @person.user_text = "<h2>About Me</h2><p>I'd like to accomplish the following three goals (professional or personal) by the time I graduate:<ol><li>Goal 1</li><li>Goal 2</li><li>Goal 3</li></ol></p>"
    end


    respond_to do |format|

#      error_message = ""
#      if params[:create_google_email]
#         password = 'just4now' + Time.now.to_f.to_s[-4,4] # just4now0428
#         status = @person.create_google_email(password)
#         if status.is_a?(String)
#           error_message += "Google account not created. " + status + "</br></br>"
#         else
#          send_email([@person.personal_email, @person.email], @person.email, generate_message(@person, password))
#         end
#      end
#      if params[:create_twiki_account]
#        status = @person.create_twiki_account
#        error_message +=  'TWiki account was not created.<br/></br>' unless status
#        status = @person.reset_twiki_password
#        error_message +=  'TWiki account password was not reset.</br>' unless status
#      end

      if @person.save
        create_google_email = params[:create_google_email]
        create_twiki_account = params[:create_twiki_account]
        create_yammer_account = false #params[:create_yammer_account]
        Delayed::Job.enqueue(PersonJob.new(@person.id, params[:create_google_email], params[:create_twiki_account], params[:create_yammer_account])) unless params[:create_google_email].nil? && params[:create_twiki_account].nil? && params[:create_yammer_account].nil?
                                      #          job = PersonJob.new(@person.id, params[:create_google_email], params[:create_twiki_account]) unless params[:create_google_email].nil? &&  params[:create_twiki_account].nil?
                                      #          job.perform

                                      #        flash[:error] = error_message unless error_message.blank?

        flash[:notice] = 'Person was successfully created.'
        format.html { redirect_to(@person) }
        format.xml { render :xml => @person, :status => :created, :location => @person }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.xml
  def update
#    if !(current_user.is_admin? || current_user.is_staff?)
#      flash[:error] = 'You don''t have permission to do this action.'
#      redirect_to(people_url) and return
#    end

    @person = Person.find(params[:id])
    @person.updated_by_user_id = current_user.id
    @strength_themes = StrengthTheme.all

    respond_to do |format|

#      if @person.save_without_session_maintenance
      if @person.update_attributes(params[:person])
        flash[:notice] = 'Person was successfully updated.'
        format.html { redirect_to(@person) }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  def revert_to_version
    @person = Person.find(params[:id])
    @person.revert_to! params[:version_id]
    redirect_to :action => 'show', :id => @person
  end

  def robots
    logger.info("curriculum comment: robot detected")
    format.html # index.html.erb
  end

  # DELETE /people/1
  # DELETE /people/1.xml
  def destroy
    if !current_user.is_admin?
      flash[:error] = 'You don' 't have permission to do this action.'
      redirect_to(people_url) and return
    end

    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to(people_url) }
      format.xml { head :ok }
    end
  end


  def my_teams
    @person = Person.find(params[:id])
    person_id = @person.id.to_i
    if (current_user.id != person_id)
      unless (current_user.is_staff?)||(current_user.is_admin?)

app/helpers/people_helper.rb
module PeopleHelper

  def display_location(person)
    return nil if (person.work_city.nil? && person.work_state.nil? && person.work_country.nil?)
    return "#{person.work_state} #{person.work_country}" if person.work_city.nil?
    return "#{person.work_city}, #{person.work_state} #{person.work_country}"

  end


end

app/views/people/_show_telephones.html.erb
<% @person.telephones.each { |phone|  %>
<%=h phone %><br/>
<% } %>

app/views/people/_team_listing.html.erb
<% reset_cycle %>
<table class="twikiTable" cellpadding="0" cellspacing="0" width="100%">
  <tr>
    <th>Course</th>
    <th>Team</th>
    <th></th>
    <th></th>
    <th>Semester</th>
    <th>Year</th>
    <th width="100">Faculty</th>
    <th width="100">Faculty</th>
    <th>&nbsp;</th>
  </tr>
  <% teams.each do |team|%>
    <tr class=<%= cycle('twikiTableOdd', 'twikiTableEven')%> >
        <td><%=h team.course.name %></td>
      <% if !team.twiki_space.nil? && !team.twiki_space.empty? %>
        <td class="twikiFirstCol"><a href='<%=h team.twiki_space%>'><%=h team.name %></a></td>
      <% else %>
        <td class="twikiFirstCol"><%=h team.name %></td>
      <% end %>
      <% if !(team.email.nil? || team.email.empty?) %>
        <td><a href='mailto:<%=h team.email %>'><%= image_tag("/images/email.gif", :width=>"12", :height=>"9", :border=>0) %></a></td>
      <% else %>
         <td> &nbsp; </td>
      <% end %>
      <% if !team.tigris_space.nil? && team.tigris_space.empty? %>
        <td><a href='<%=h team.tigris_space %>'><%= image_tag("/images/tigris.gif", :width=>"16", :height=>"16", :border=>0) %></a></td>
      <% else %>
        <td> &nbsp; </td>
      <% end %>
        <td><%=h team.course.semester %></td>
        <td><%=h team.course.year %></td>
      <% if team.primary_faculty %>
      <td><%= twiki_user_link(team.primary_faculty.twiki_name, team.primary_faculty.human_name) %></td>
      <% else %>
      <td>&nbsp;</td>
      <% end %>
      <% if team.secondary_faculty %>
      <td><%= twiki_user_link(team.secondary_faculty.twiki_name, team.secondary_faculty.human_name) %></td>
      <% else %>
      <td>&nbsp;</td>
      <% end %>
      <td><%= link_to 'Show', course_team_path(team.course_id, team) %></td>
    </tr>
  <% end %>
  </table>

app/views/people/advanced.erb
<% content_for :title, 'People' %>

<% content_for :tablesorter do %>
  <%= javascript_include_tag 'tablesorter' %>
  <%= javascript_include_tag 'tablesorter_filter' %>
<script type="text/javascript">
$(document).ready(function() 
    {
       if ($("#filterBoxOne").prop("disabled") == true)
       {
         $('#filterBoxOne').val('');
         $('#filterBoxOne').removeAttr("disabled");
         $('#filterBoxOne').focus();
        }
        $("#people_table").tablesorter({widgets: ['zebra'],         
                                        headers: {2: {sorter: false}  },
                                        sortList: [[0,0], [1,0]]})
            .tablesorterFilter({ filterContainer: $("#filterBoxOne"),
                filterClearContainer: $("#filterClearOne"),
                filterColumns: [0, 1, 3, 4, 5],
                filterCaseSensitive: false
            });        

        //scroll the message box to the top offset of browser's scrool bar
        $(window).scroll(function()
        {
          $('#image_box').animate({top:$(window).scrollTop()+"px" },{queue: false, duration: 350});
        });
        //when the close button at right corner of the message box is clicked
        $('#close_image_box').click(function()
        {
          //the messagebox gets scroll down with top property and gets hidden with zero opacity
          $('#image_box').animate({ top:"+=15px",opacity:0 }, "slow");
          $('#image_box').hide();
        });

        //hovering over a line selects it
        $("tr").hover(
        function () {
          $(this).addClass("hover");
        },
        function () {
          $(this).removeClass("hover");
        });
      }
);

function toggleStudents()
{
  /* we don't use .toggle since the state may be inaccurate from a page reload */
  if ($('#student_checkbox').is(':checked')) {
    $(".student").show();
  } else {
    $(".student").hide();
  }
  $("#filterBoxOne").trigger("keyup");
}

function toggleStaff()
{
  if ($('#staff_checkbox').is(':checked')) {
    $(".staff").show();
  } else {
    $(".staff").hide();
  }
  $("#filterBoxOne").trigger("keyup");
}

function updateImage(uri,label)
{
 $('#image_box_image').prop("src", uri);

 $('#image_box_label').text(label);
}

</script>
<% end %>

<h1>Listing people</h1>
<div class="right_link" ><%= link_to 'See users book', :action=>'index' %><br/><%= link_to 'See photo book', :action=>'photo_book' %></div>
<div style="float:none"><%= render :partial => "tablesorter_filter_box" %><label>Show Students</label><input type="checkbox" id="student_checkbox" onchange="toggleStudents()" value="1" checked="checked" />
  <label>Show Staff</label><input type="checkbox" id="staff_checkbox" onchange="toggleStaff()" value="1" checked="checked" />
</div>

<div id="image_box">
  <%= image_tag("/images/mascot.jpg", :width=>"150", :alt=>"Temporary Picture", :id=>"image_box_image")%><%= image_tag("/images/tablesorter/cross.png", :width=>"16", :height=>"16", :alt=>"Close Me", :style=>"float:right;cursor:pointer", :id=>"close_image_box") %>
  <div id='image_box_label'></div>
</div>

<% if current_user && (current_user.is_admin? || current_user.is_staff?) %>
<%= link_to 'New person', new_person_path %>
<% end %>

<table id="people_table" class="tablesorter">
  <thead>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Icons</th>
    <th>Graduation year</th>
    <th>Graduate program</th>
    <th>Graduate track</th>
  </tr>
</thead>
<tbody>
<% for person in @people %>

<tr class="tablesorter <%if person.is_student %>student<% end %> <% if person.is_staff %>staff<%end%>"  onmouseover="updateImage('<%= image_path(person.image_uri) %>','<%=person.human_name%>')">
    <td><%= twiki_user_link(person.twiki_name, person.first_name) %></td>
    <td><%= twiki_user_link(person.twiki_name, person.last_name) %></td>    
    <td><a href='http://info.sv.cmu.edu/twiki/bin/view/Main/<%= person.twiki_name %>' target='_top'><%= image_tag('/images/twiki.gif', :width=>'16', :height=>'16', :border=>"0", :alt=>"My TWiki page", :title=>"My TWiki page") %></a>
        <% if person.is_adobe_connect_host %><%= image_tag("/images/connect.gif", :width=>"16", :height=>"16", :alt=>"Adobe Connect Host", :title=>"I am Adobe Connect Host") %><% end %>
        <% if current_user.is_staff? || current_user.is_admin? %>
        <%= link_to image_tag("/images/my_teams2.gif", :width=>"16", :height=>"16", :alt=>"My Teams", :title=>"My Teams"), my_teams_path(person.id) %>
        <% end %>
    </td>
    <td><%=h person.graduation_year %></td>
    <td><%=h person.masters_program %></td>
    <td><%=h person.masters_track %></td>
    <td><%= link_to 'Show', person %></td>
<% if current_user && current_user.is_staff? %>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
<% else %>
    <td>&nbsp;</td>
<% end %>
<!--
<% if current_user && current_user.is_admin? %>
    <td><%= link_to 'Destroy', person, :confirm => 'Are you sure?', :method => :delete %></td>
<% else %>
    <td>&nbsp;</td>
<% end %>
-->
  </tr>
<% end %>
</tbody>
</table>

<br />

<% if current_user && (current_user.is_admin? || current_user.is_staff?) %>
<%= link_to 'New person', new_person_path %>
<% end %>

app/views/people/robots.html.erb
<h1>Robots page</h1>

We believe that you are a robot. This part of the application only works if you have HTTP_REFERER set. Sorry.

app/views/people/show.html.erb
<% content_for :title, @person.human_name + " - Contact Information"%>


<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 


<table><tr valign="top"><td>
  <div class="user_photo"><%= image_tag(@person.image_uri) %></div>
  </td><td>&nbsp;</td><td>
<h1><%=h @person.human_name %></h1>
  <div align="right" valign="top" style="position:absolute;top:280px;left:890px;font-size:11px;" >
    <%= link_to 'Edit', edit_person_path(@person) %> |
    <%= link_to 'Back', people_path %>
  </div>

<% unless @person.pronunciation.blank? %>
<div class="header_subtext">Pronounced <%=h @person.pronunciation %></div>
<% end %>
<table border="1" cellspacing="0" cellpadding="0" style="border-width: 1px;" class="cmu_table ">
<tr class="cmu_table_odd"><td>Organization:</td>
    <td><% if @person.organization_name %><% if @person.title %><%=h @person.title%><br/><%end%><%=h @person.organization_name %><%else%>&nbsp;<%end%></td></tr>
<tr class="cmu_table_even"><td>Location:</td>
    <td><% if display_location(@person) %><%=h display_location(@person) %><%else%>&nbsp;<%end%></td></tr>
<tr class="cmu_table_odd"><td><p>Telephone:</p></td>
    <td><%= render :partial => 'show_telephones' %></td></tr>
<tr class="cmu_table_even"><td>E-mail:</td>
    <td><%=h @person.email %></td></tr>
<% if @person.is_staff %>
<tr class="cmu_table_odd"><td>Office:</td>
    <td><%=h @person.office %></td></tr>
<tr class="cmu_table_even"><td>Office Hours:</td>
    <td><%=h @person.office_hours %></td></tr>
<% end %>

<% if @person.is_student %>
<tr class="cmu_table_odd"><td colspan="2">
    I am a <% if @person.is_part_time %> part time <% else %> full time <% end %> student in the <%=h @person.masters_program %> program<% if !(@person.masters_track.nil? || @person.masters_track.empty?) %> (<%=h @person.masters_track %> Track)<% end %>.
    <% if !(@person.graduation_year.nil? || @person.graduation_year.empty?) %>
  Class of <%=h @person.graduation_year - 1 %>.
    <% end %>
<% unless @person.local_near_remote.blank? || @person.local_near_remote=="Unknown" %><br/> I am a  <%=h @person.local_near_remote.downcase %> student.<% end %>
  </td></tr>
<% end %>
<tr class="cmu_table_odd"><td>&nbsp;</td>
  <td>
    <% if (current_user.is_staff? || current_user.is_admin?) && @person.teams.count > 0 %>
        <%= link_to "My teams", my_teams_path(@person) %>
        <%= link_to image_tag("/images/my_teams2.gif", :id => "icon", :width=>"16", :height=>"16", :alt=>"My Teams", :title=>"My Teams"), my_teams_path(@person) %>
    <% end %>
  </td></tr>

</table>



</td></tr></table>


  <%= sanitize @person.biography, :tags => %w(table tr td p br span img a h1 h2 h3 ul ol li), :attributes => %w(id class style) %>

<h2>Helpful info</h2>
Skype: <%=h @person.skype %><br />
<% unless @person.tigris.blank? %>Tigris: <%=h @person.tigris %><br /><% end %>
Github: <%=h @person.github %><br />
Personal email: <%=h @person.personal_email %><br />

    <%= sanitize @person.user_text, :tags => %w(table tr td p br span img a h1 h2 h3 ul ol li), :attributes => %w(id class style) %>

<h2>Strength Finders</h2>
<p>For more information about Clifton's Strength Finders, visit <a href="http://www.strengthquest.com">Strength Quest</a></p>    
    <%= render :partial => 'show_strength_theme', :locals=>{:number => 1, :strength_theme => @person.strength1} %>
    <%= render :partial => 'show_strength_theme', :locals=>{:number => 2, :strength_theme => @person.strength2} %>
    <%= render :partial => 'show_strength_theme', :locals=>{:number => 3, :strength_theme => @person.strength3} %>
    <%= render :partial => 'show_strength_theme', :locals=>{:number => 4, :strength_theme => @person.strength4} %>
    <%= render :partial => 'show_strength_theme', :locals=>{:number => 5, :strength_theme => @person.strength5} %>
<% if @person.strength1.nil? %>
<% end %>

<h1><%=h @person.human_name %></h1>    
  <div class="rounded staff">
  <%= image_tag("/images/professor.jpg", :size => "50x50", :border=>"0", :alt=>"These fields can be edited by a faculty role") %>
  <span class="instructions">These fields can be edited by faculty.</span>
  <%= render :partial => 'show_faculty_fields', :locals=>{:f => f, :person => @person} %>
  </div>

  <div class="rounded admin">
  <%= image_tag("/images/admin.jpg", :size => "50x50", :border=>"0", :alt=>"These fields can be edited by an admin role") %>
  <span class="instructions">These fields can be edited by admin.</span>
  <%= render :partial => 'show_admin_fields', :locals=>{:f => f, :person => @person} %>
  </div>


<% end %>

<br/><br/>


<% for version in @person.versions.reverse %>
Version <%= version.version %>
<%= link_to '(revert)', { :action => 'revert_to_version', :version_id => version.version, :id => @person}, {:confirm => "Are you sure?" } %>
<% if @person.version == version.version %>
(currently on page)
<% else %>
<%= link_to '(preview)', :action => 'show', :version_id => version.version, :id => @person %>
<% end %>
<% updated_by = Person.find(:first, :conditions=> ["id = ?", version.updated_by_user_id]) %><% if !updated_by.nil? %>by <%=h updated_by.human_name %><% end %>
on <%=l version.updated_at, :format => :detailed %>
 <br/>
<% end %>
<br/><br/>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>