config/routes.rb
CMUEducation::Application.routes.draw do
  resources :search, :only => [:index]
  resources :deliverables
  match '/people/:id/my_deliverables' => 'deliverables#my_deliverables', :as => :my_deliverables
  match '/deliverables/:id/feedback' => 'deliverables#edit_feedback', :as => :deliverable_feedback
  match '/sponsored_projects/:id/archive' => 'sponsored_projects#archive', :as => :archive_sponsored_project
  match '/sponsored_project_sponsors/:id/archive' => 'sponsored_project_sponsors#archive', :as => :archive_sponsored_project_sponsor
  match '/sponsored_project_allocations/:id/archive' => 'sponsored_project_allocations#archive', :as => :archive_sponsored_project_allocation
  resources :sponsored_projects
  resources :sponsored_project_sponsors
  resources :sponsored_project_allocations
  resources :sponsored_project_efforts
  match 'delayed_system_jobs/' => 'delayed_system_jobs#index'
  resources :delayed_system_jobs
  resources :rss_feeds
  resources :curriculum_comment_types
  match '/curriculum_comments/test_page' => 'curriculum_comments#test_page'
  resources :curriculum_comments
  resources :scotty_dog_sayings
  resources :project_types
  resources :projects
  resources :task_types
  match '/effort_logs/update_task_type_select' => 'effort_logs#update_task_type_select', :as => :update_task_type_select
  match '/effort_logs/effort_for_unregistered_courses' => 'effort_logs#effort_for_unregistered_courses'
  resources :effort_logs
  resources :effort_log_line_items
  resources :course_numbers
  resources :course_configurations
  match '/courses/current_semester' => 'courses#current_semester', :as => :current_semester
  match '/courses/next_semester' => 'courses#next_semester', :as => :next_semester
  constraints({:id => /.*/}) do
    resources :mailing_lists
    resources :pages do
      collection do
        post :reposition
      end
    end
  end

  resources :course_navigations
  resources :courses do
    resources :teams do
    end
    member do
      get :configure
    end
  end

  match '/courses/:course_id/peer_evaluations' => 'peer_evaluation#index_for_course', :via => :get, :as => "peer_evaluations"
  match '/courses/:course_id/teams/:id/peer_evaluation' => 'teams#peer_evaluation', :via => :get, :as => "peer_evaluation"
  match '/courses/:course_id/teams/:id/peer_evaluation_update' => 'teams#peer_evaluation_update', :via => :post, :as => "peer_evaluation_update"
  match 'peer_evaluation/edit_setup/:id' => 'peer_evaluation#edit_setup', :as => :setup_peer_evaluation
  match 'peer_evaluation/edit_evaluation/:id' => 'peer_evaluation#edit_evaluation', :as => :edit_peer_evaluation
  match 'peer_evaluation/edit_report/:id' => 'peer_evaluation#edit_report', :as => :report_peer_evaluation

  match '/effort_reports/campus_week' => 'effort_reports#campus_week'
  match '/effort_reports/campus_semester' => 'effort_reports#campus_semester'
  match '/effort_reports/course/:course_id' => 'effort_reports#course'
  resources :effort_reports
  match '/people/class_profile' => 'people#class_profile'
  match '/people/advanced' => 'people#advanced' #Just in case anyone bookmarked this url
  match '/people/photo_book' => 'people#photo_book'
  match '/people/:id/my_courses' => 'people#my_courses', :as => :my_courses
  match '/people/:id/my_teams' => 'people#my_teams', :as => :my_teams
  resources :people
  resources :suggestions
  match '/teams' => 'teams#index_all', :as => :teams

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  #resources :users
  #resource :user_session

  #match '/login_google' => 'user_sessions#login_google', :as => :login_google
  #match '/logout' => "user_sessions#destroy", :as => :logout


  match '/load_chart' => 'effort_reports#load_chart', :as => :load_chart
  match 'people/twiki/:twiki_name' => 'people#show_by_twiki'
  match 'twiki/teams' => 'teams#twiki_index'
  match 'twiki/teams/new' => 'teams#twiki_new'
  match 'courses/:course_id/teams_photos' => 'teams#index_photos'
  match 'courses/:course_id/past_teams_list' => 'teams#past_teams_list', :as => :past_teams_list
  match 'courses/:course_id/export_to_csv' => 'teams#export_to_csv'
  match 'courses/:course_id/deliverables' => 'deliverables#index_for_course', :as => :course_deliverables
  match 'effort_reports/:id/week/:week' => 'effort_reports#show_week'
  match '/:controller(/:action(/:id))'
  match '/new_features' => 'welcome#new_features', :as => :new_features
  match '/config' => 'welcome#configuration', :as => :config
  match '/' => 'welcome#index', :as => :root
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
#  layout 'cmu_sv_simple'
  layout 'cmu_sv'

  def index
    @rss_feeds = RssFeed.all

    if (current_person.nil?)
      @courses_registered_as_student = []
    else
      @courses_registered_as_student = current_person.get_registered_courses
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @courses }
    end
  end

  def new_features

  end

  def configuration

  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/configuration.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title></title>
</head>
<body>


<div>Google Username: <%= GOOGLE_USERNAME %></div>
<div>Google Domain: <%= GOOGLE_DOMAIN %></div>
<br/>
<div>TWiki Username: <%= TWIKI_USERNAME %></div>
<div>TWiki Url: <%= TWIKI_URL %></div>
<br/>


</body>
</html>

app/views/welcome/index.html.erb
<% content_for :title, 'CMU-SV Rails Application' %>

<%# render :partial=>'rss_feeds/index', :locals => {:rss_feeds => @rss_feeds} %>

<% if current_user %>
  <h1>My courses</h1>
  <% @courses_registered_as_student.each do |course| %>
    <p><%= link_to course.name, course_path(course) %></p>
    <%# render :partial => "/courses/show_actions" ,:locals => { :course => course } %>
  <% end %>
<% end  %>

<h2>Experimental features</h2>
            <form action="<%= search_index_path %>" id="searchform" method="get" role="search">
<div>
                    <label for="s" class="screen-reader-text">Search for:</label>
    <input type="text" id="query" name="query" value="">
    <input type="submit" value="Search" id="searchsubmit">
    (Note: only searches through curriculum pages saved after Orientation 2011. This will move into the layout once done.)
</div>
            </form>

<% if current_user && (current_user.is_staff || current_user.is_admin) %>
<h2>Faculty views</h2>
<p><a href="/teams">All teams</a></p>
<h2>Admin notes</h2>
<p>The current semester is <%= current_semester() %>. The current time is <%= l Time.now, :format => :chatty %> </p>
<% end %>

<h2>New features</h2>
<p><%= link_to "New Features", new_features_path %></p>
<p><%= link_to "Google Mailing Lists", mailing_lists_path %></p>

<% if current_user && current_user.is_admin %>
<h2>Admin only</h2>
    <p><%= link_to "Config", config_path %></p>
<% end %>

app/views/welcome/new_features.erb
<% content_for :title, 'New Features' %>

<p>5/11/2011 - <b>Deliverables</b> - Thanks to Team Super 8 for Deliverable Submission feature. We can now move off of tigris.org MFSE (Story 1 Fall 2010). </p>

<p>4/19/2011 - <b>Upload Profile Photo</b> - Thanks to Team Veracity for allowing users to change their photo </p>

<p>4/15/2011 - <b>Team Formation Helper</b> - Thanks to Team Super8 for creating a helper that allows faculty to see who has been on which team in the past and exporting it out to csv. This is MFSE - Story 6 Fall 2010.</p>

<p>4/15/2011 - <b>Edit Profile</b> - Thanks to Team Super8 for polishing up the Edit Profile code from the MFSE (Story 11 Fall 2010).</p>

<p>4/1/2011 - <b>Sponsored Project Research</b> - Chris Jensen and Todd Sedano added code to make Hector's life a bit easier.</p>

<p>10/15/2010 - <b>CMS</b> prototype of curriculum website is now ready</p>

<p>9/30/2010 - <b>Papers</b> prototype of papers is now ready.</p>

<p>7/1/2010 - <b>New production environment</b> -- our move to Heroku happened around here</p>

<p>5/15/2010 - <b>Auto create google and twiki accounts</b> When a new user is created, the system can create a correspoinding sv.cmu.edu email account and twiki account.</p>

<p>4/30/2010 - Thanks to Suresh Rajasekaran for writing code to see if a user is logging effort against the wrong courses.</p>

<p>4/1/2010 - <b>Team Email Lists</b> - are now created automatically - Thanks to Team Deming for providing this code in MfSE.</p>
<p>3/18/2010 - <b>Mailing Lists</b> - We can now see what <%= link_to "Google Mailing Lists", mailing_lists_path %> exist and who is on each one</p>

<p>3/14/2010 - Effort Logs can be created on Monday of the following week - Thanks to Team Crosby for providing this code in Mfse.
Special thanks for providing all the test cases to verify that the code works properly.</p>

<p>3/2/2010 - <b>My Teams (faculty view)</b> - Thanks to Team Juran for providing this code in MfSE.
Faculty can now easily see which teams they are teaching</p>

<p>2/23/2010 - <b>My Teams</b> - Thanks to Team Juran for providing this code in MfSE. 
Students can now easily see which teams they are on</p>

<p>2/5/2010 - <b>Peer Evalution tool integrated!</b>- Russel Reed wrote the initial version of the Peer
Evaluation tool which allows faculty members to record student learning objectives.
Student teams can do a 360 peer evaluation. Faculty can quickly see who hasn't
done the evaluation. The tool also generates a draft report for each student.
This entire process used to be very tedious for the faculty since we had to both
setup Survey Monkey and manually generate the student reports.
</p>


<p>
12/31/2009 - Added in Team Deming code from MfSE for sorting courses. Special
thanks to Evgueni Ratchev, Harish Suvarna, Gayatri Picha, Greg Hilton, and
Andrew Retelle for making this possible.
</p>

<p>
12/16/2009 - <b>RSS Integration</b> - Any news articles published on http://sv.cmu.edu
are linked from the rails app's home page.
</p>

<p>
11/30/2009 - Integrated twiki user page into rails database. Started the process
of moving user data from TWiki to rails database
</p>

<p>10/26/2009 - Photo Book created</p>

<p>10/22/2009 - List all email addresses for a course (for Ron)</p>

<p>10/19/2009 - configured apache and mongrel to allow the browser to cache static
content (ie images, javascript, css)</p>

<p>10/16/2009 - This project is now under continuous integration on a build machine!</p>

<p>10/7/2009 - Effort Logs - Faculty now get weekly reminders to check effort logs
for their courses.</p>

<p>9/4/2009 - User Data - this project now has all the data fields found in the
twiki application.</p>

<p>6/26/2009 - <b>Curriculum Website Comments</b> - Implemented feature suggested by
Mania Orand.</p>

<p>5/22/2009 - <b>Scotty Dog</b> is born and sends his first email.</p>

<p>3/25/2009 - Tablesorter introducted for people data and course data.</p>

<p>2/3/2009 - Effort Log for faculty. Now faculty can dog food!</p>

<p>1/16/2009 - <b>Suggestion Box</b> for new features and bug fixes</p>

<p>9/30/2008 - <b>Effort Reports</b></p>

<p>8/14/2008 - Andrew Id integration. </p>

<p>7/22/2008 - <b>Effort Log for students.</b></p>

<p>7/1/2008 - project started</p>