config/routes.rb
CMUEducation::Application.routes.draw do
  resources :search, :only => [:index]
  resources :deliverables
  match '/people/:id/my_deliverables' => 'deliverables#my_deliverables', :as => :my_deliverables
  match '/deliverables/:id/feedback' => 'deliverables#edit_feedback', :as => :deliverable_feedback
  match '/sponsored_projects/:id/archive' => 'sponsored_projects#archive', :as => :archive_sponsored_project
  match '/sponsored_project_sponsors/:id/archive' => 'sponsored_project_sponsors#archive', :as => :archive_sponsored_project_sponsor
  match '/sponsored_project_allocations/:id/archive' => 'sponsored_project_allocations#archive', :as => :archive_sponsored_project_allocation
  resources :sponsored_projects
  resources :sponsored_project_sponsors
  resources :sponsored_project_allocations
  resources :sponsored_project_efforts
  match 'delayed_system_jobs/' => 'delayed_system_jobs#index'
  resources :delayed_system_jobs
  resources :rss_feeds
  resources :curriculum_comment_types
  match '/curriculum_comments/test_page' => 'curriculum_comments#test_page'
  resources :curriculum_comments
  resources :scotty_dog_sayings
  resources :project_types
  resources :projects
  resources :task_types
  match '/effort_logs/update_task_type_select' => 'effort_logs#update_task_type_select', :as => :update_task_type_select
  match '/effort_logs/effort_for_unregistered_courses' => 'effort_logs#effort_for_unregistered_courses'
  resources :effort_logs
  resources :effort_log_line_items
  resources :course_numbers
  resources :course_configurations
  match '/courses/current_semester' => 'courses#current_semester', :as => :current_semester
  match '/courses/next_semester' => 'courses#next_semester', :as => :next_semester
  constraints({:id => /.*/}) do
    resources :mailing_lists
    resources :pages do
      collection do
        post :reposition
      end
    end
  end

  resources :course_navigations
  resources :courses do
    resources :teams do
    end
    member do
      get :configure
    end
  end

  match '/courses/:course_id/peer_evaluations' => 'peer_evaluation#index_for_course', :via => :get, :as => "peer_evaluations"
  match '/courses/:course_id/teams/:id/peer_evaluation' => 'teams#peer_evaluation', :via => :get, :as => "peer_evaluation"
  match '/courses/:course_id/teams/:id/peer_evaluation_update' => 'teams#peer_evaluation_update', :via => :post, :as => "peer_evaluation_update"
  match 'peer_evaluation/edit_setup/:id' => 'peer_evaluation#edit_setup', :as => :setup_peer_evaluation
  match 'peer_evaluation/edit_evaluation/:id' => 'peer_evaluation#edit_evaluation', :as => :edit_peer_evaluation
  match 'peer_evaluation/edit_report/:id' => 'peer_evaluation#edit_report', :as => :report_peer_evaluation

  match '/effort_reports/campus_week' => 'effort_reports#campus_week'
  match '/effort_reports/campus_semester' => 'effort_reports#campus_semester'
  match '/effort_reports/course/:course_id' => 'effort_reports#course'
  resources :effort_reports
  match '/people/class_profile' => 'people#class_profile'
  match '/people/advanced' => 'people#advanced' #Just in case anyone bookmarked this url
  match '/people/photo_book' => 'people#photo_book'
  match '/people/:id/my_courses' => 'people#my_courses', :as => :my_courses
  match '/people/:id/my_teams' => 'people#my_teams', :as => :my_teams
  resources :people
  resources :suggestions
  match '/teams' => 'teams#index_all', :as => :teams

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  #resources :users
  #resource :user_session

  #match '/login_google' => 'user_sessions#login_google', :as => :login_google
  #match '/logout' => "user_sessions#destroy", :as => :logout


  match '/load_chart' => 'effort_reports#load_chart', :as => :load_chart
  match 'people/twiki/:twiki_name' => 'people#show_by_twiki'
  match 'twiki/teams' => 'teams#twiki_index'
  match 'twiki/teams/new' => 'teams#twiki_new'
  match 'courses/:course_id/teams_photos' => 'teams#index_photos'
  match 'courses/:course_id/past_teams_list' => 'teams#past_teams_list', :as => :past_teams_list
  match 'courses/:course_id/export_to_csv' => 'teams#export_to_csv'
  match 'courses/:course_id/deliverables' => 'deliverables#index_for_course', :as => :course_deliverables
  match 'effort_reports/:id/week/:week' => 'effort_reports#show_week'
  match '/:controller(/:action(/:id))'
  match '/new_features' => 'welcome#new_features', :as => :new_features
  match '/config' => 'welcome#configuration', :as => :config
  match '/' => 'welcome#index', :as => :root
end

app/models/sponsored_project.rb
class SponsoredProject < ActiveRecord::Base
  validates_presence_of :name, :sponsor_id
  validates_uniqueness_of :name
  validates_inclusion_of :is_archived, :in => [true, false]

  scope :current, :conditions => {:is_archived => false}
  scope :archived, :conditions => {:is_archived => true}

  default_scope :order => "SPONSOR_ID ASC, NAME ASC"

  belongs_to :sponsor, :class_name => "SponsoredProjectSponsor"
end

app/controllers/sponsored_projects_controller.rb
class SponsoredProjectsController < ApplicationController

  before_filter :authenticate_user!

  layout 'cmu_sv'

  def index
    if has_permissions_or_redirect
      @projects = SponsoredProject.current
      @sponsors = SponsoredProjectSponsor.current
    end
  end

  def new
    if has_permissions_or_redirect
      store_previous_location
      @project = SponsoredProject.new
      @sponsors = SponsoredProjectSponsor.current
    end
  end

  def edit
    if has_permissions_or_redirect
      @project = SponsoredProject.find(params[:id])
      @sponsors = SponsoredProjectSponsor.current
    end
  end

  def create
    if has_permissions_or_redirect
      @project = SponsoredProject.new(params[:sponsored_project])
      @sponsors = SponsoredProjectSponsor.current

      if @project.save
        flash[:notice] = 'Project was successfully created.'
        redirect_back_or_default(sponsored_projects_path)
      else
        render "new"
      end
    end
  end

  def update
    if has_permissions_or_redirect
      @project = SponsoredProject.find(params[:id])
      @sponsors = SponsoredProjectSponsor.current

      if @project.update_attributes(params[:sponsored_project])
        flash[:notice] = 'Project was successfully updated.'
        redirect_to(sponsored_projects_path)
      else
        render "edit"
      end
    end
  end

  def archive
    if has_permissions_or_redirect
      @project = SponsoredProject.find(params[:id])
      if @project.update_attributes({:is_archived => true})
        flash[:notice] = 'Project was successfully archived.'
        redirect_to(sponsored_projects_path)
      else
        flash[:notice] = 'Project could not be archived.'
        redirect_to(sponsored_projects_path)
      end
    end
  end

  protected
  def has_permissions_or_redirect
    unless current_user.permission_level_of(:admin)
      flash[:error] = t(:no_permission)
      redirect_to(root_path)
      return false
    end
    return true
  end


end

app/views/sponsored_projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 

  <table>
    <tr><td><%= f.label :name %></td><td><%= f.text_field :name, :size => "95"%></td></tr>
    <tr><td><%= f.label :sponsor %></td><td><%= f.select :sponsor_id, @sponsors.collect{|item| [item.name, item.id]} %></td></tr>
  </table>

  <br />
  <%= f.submit button_name %>
  <br/>
  <br/>
<% end %>

app/views/sponsored_projects/edit.html.erb
<h1>Edit Sponsored Project</h1>

<%= render :partial => "form", :locals => { :button_name => "Update" } %>


<%= link_to 'Back', sponsored_projects_path %>
<br/>
<br/>

app/views/sponsored_projects/index.html.erb
<h1>Sponsored Projects</h1>
<div class="right_link" ><%= link_to 'Allocations', sponsored_project_allocations_url %><br/>
<%= link_to "This month's efforts", sponsored_project_efforts_url %></div>
<table cellpadding="3">
  <tr><th>Sponsor</th><th>Name</th><th>&nbsp;</th><th>&nbsp;</th></tr>
  <% @projects.each do |project| %>
      <tr>
        <td><%= project.sponsor.name %></td>
        <td><%= project.name %></td>
        <td><%= link_to 'Edit', edit_sponsored_project_path(project) %></td>
        <td><%= link_to 'Archive', archive_sponsored_project_path(project) %></td>
      </tr>
  <% end %>
<tr><td colspan="3"><%= link_to 'New project', new_sponsored_project_path %></td></tr>
</table>


<h1>Sponsors</h1>
<table cellpadding="3">
  <tr><th>Name</th><th>&nbsp;</th><th>&nbsp;</th></tr>
  <% @sponsors.each do |sponsor| %>
      <tr>
        <td><%= sponsor.name %></td>
        <td><%= link_to 'Edit', edit_sponsored_project_sponsor_path(sponsor) %></td>
        <td><%= link_to 'Archive', archive_sponsored_project_sponsor_path(sponsor) %></td>
      </tr>
  <% end %>
  <tr><td colspan="2"><%= link_to 'New sponsor', new_sponsored_project_sponsor_path %></td></tr>
</table>
<br/>
<br/>

app/views/sponsored_projects/new.html.erb
<h1>New Sponsored Project</h1>

<%= render :partial => "form", :locals => { :button_name => "Create" } %>


<%= link_to 'Back', sponsored_projects_path %>
<br/>
<br/>